import { lazy } from 'react'

export const CoursesPage = lazy(() => import('../pages/academics/CoursesPage'))
export const ContentLibraryPage = lazy(() => import('../pages/academics/ContentLibraryPage'))
export const CurrentAffairsPage = lazy(() => import('../pages/academics/CurrentAffairsPage'))
export const BooksPage = lazy(() => import('../pages/marketing/BooksPage'))
export const WebsitePage = lazy(() => import('../pages/marketing/WebsitePage'))
export const BannersPage = lazy(() => import('../pages/marketing/BannersPage'))
export const BlogsPage = lazy(() => import('../pages/marketing/BlogsPage'))
export const CouponsPage = lazy(() => import('../pages/users/CouponsPage'))
export const EnquiriesPage = lazy(() => import('../pages/crm/EnquiriesPage'))
export const LeadsPage = lazy(() => import('../pages/crm/LeadsPage'))
export const HelpDeskPage = lazy(() => import('../pages/crm/HelpDeskPage'))
export const PushNotificationsPage = lazy(() => import('../pages/crm/PushNotificationsPage'))
export const AnalyticsPage = lazy(() => import('../pages/AnalyticsPage'))
export const AdminManagementPage = lazy(() => import('../pages/users/AdminManagementPage'))
export const AdminAccessTypesPage = lazy(() => import('../pages/users/AdminAccessTypesPage'))
export const RoleAccessMatrixPage = lazy(() => import('../pages/users/RoleAccessMatrixPage'))
export const CenterManagementPage = lazy(() => import('../pages/users/CenterManagementPage'))
export const ModuleListPage = lazy(() => import('../pages/ModuleListPage'))
