import { Layers } from 'lucide-react'

export const CATEGORY_HUB_TABS = [
  { id: 'exam-category', label: 'Exam Category' },
  { id: 'exam-sub-category', label: 'Exam Sub-Category' },
  { id: 'subject', label: 'Subject' },
  { id: 'topic', label: 'Topic' },
  { id: 'teachers', label: 'Teachers' },
]

export const CATEGORY_HUB_SECTIONS = {
  'exam-category': {
    id: 'exam-category',
    icon: Layers,
    bannerTitle: 'Exam Category',
    addLabel: 'Add Category',
    searchPlaceholder: 'Search Category',
    primaryColumn: 'Category',
    emptyTitle: 'No Exam Categories Found',
    emptyDescription: 'Create your first exam category to get started.',
    emptyCta: 'Create Category',
    filters: ['status'],
    formFields: ['name', 'description', 'status', 'icon'],
  },
  'exam-sub-category': {
    id: 'exam-sub-category',
    icon: Layers,
    bannerTitle: 'Exam Sub-Category',
    addLabel: 'Add Sub-Category',
    searchPlaceholder: 'Search Sub Category',
    primaryColumn: 'Sub-Category',
    emptyTitle: 'No Sub-Categories Found',
    emptyDescription: 'Add sub-categories under your exam categories.',
    emptyCta: 'Create Sub-Category',
    filters: ['category', 'status'],
    formFields: ['parentCategory', 'name', 'description', 'status'],
  },
  subject: {
    id: 'subject',
    icon: Layers,
    bannerTitle: 'Subjects',
    addLabel: 'Add Subject',
    searchPlaceholder: 'Search Subject',
    primaryColumn: 'Subject',
    emptyTitle: 'No Subjects Found',
    emptyDescription: 'Add subjects for your academic programs.',
    emptyCta: 'Create Subject',
    filters: ['status'],
    formFields: ['name', 'description', 'status'],
  },
  topic: {
    id: 'topic',
    icon: Layers,
    bannerTitle: 'Topics',
    addLabel: 'Add Topic',
    searchPlaceholder: 'Search Topic',
    primaryColumn: 'Topic',
    emptyTitle: 'No Topics Found',
    emptyDescription: 'Organize topics under each subject.',
    emptyCta: 'Create Topic',
    filters: ['subject', 'status'],
    formFields: ['subject', 'name', 'description', 'status'],
  },
  teachers: {
    id: 'teachers',
    icon: Layers,
    bannerTitle: 'Teachers',
    addLabel: 'Add Teacher',
    searchPlaceholder: 'Search Topic',
    primaryColumn: 'Name',
    emptyTitle: 'No Teachers Found',
    emptyDescription: 'Add faculty linked to subjects.',
    emptyCta: 'Create Teacher',
    filters: ['subject', 'status'],
    formFields: ['subject', 'name', 'description', 'status'],
    dateColumns: { created: 'Added On', modified: 'Modified On' },
  },
}
