import { Layers, GraduationCap, BookOpen, Users, FolderTree, LayoutGrid, DoorOpen, MapPin } from 'lucide-react'

/** Tab order: Programs first, then full academic hierarchy */
export const CATEGORY_HUB_TABS = [
  { id: 'programs', label: 'Programs', path: '/academics/categories/programs' },
  { id: 'exam-category', label: 'Exam Category', path: '/academics/categories/exam-category' },
  { id: 'exam-sub-category', label: 'Exam Sub-Category', path: '/academics/categories/exam-sub-category' },
  { id: 'courses', label: 'Courses', path: '/academics/categories/courses' },
  { id: 'subject', label: 'Subject', path: '/academics/categories/subject' },
  { id: 'topic', label: 'Topic', path: '/academics/categories/topic' },
  { id: 'teachers', label: 'Teachers', path: '/academics/categories/teachers' },
  { id: 'city', label: 'City', path: '/academics/categories/city' },
  { id: 'class-rooms', label: 'Class Rooms', path: '/academics/categories/class-rooms' },
]

export const DEFAULT_CATEGORY_TAB = 'programs'

export function getTabIdFromPath(pathname) {
  const match = CATEGORY_HUB_TABS.find(
    (t) => pathname === t.path || pathname.startsWith(`${t.path}/`),
  )
  return match?.id || DEFAULT_CATEGORY_TAB
}

export const CATEGORY_HUB_SECTIONS = {
  programs: {
    id: 'programs',
    icon: LayoutGrid,
    bannerTitle: 'Programs',
    bannerSubtitle: 'Manage Academic Programs',
    addLabel: 'Create Program',
    searchPlaceholder: 'Search programs...',
    primaryColumn: 'Program Name',
    emptyTitle: 'No Programs Found',
    emptyDescription: 'Create your first academic program and link courses to it.',
    emptyCta: 'Create Program',
    filters: ['status', 'centre'],
  },
  'exam-category': {
    id: 'exam-category',
    icon: Layers,
    bannerTitle: 'Exam Category',
    bannerSubtitle: 'Organize exam categories under programs',
    addLabel: 'Add Category',
    searchPlaceholder: 'Search Category',
    primaryColumn: 'Category',
    emptyTitle: 'No Exam Categories Found',
    emptyDescription: 'Create your first exam category to get started.',
    emptyCta: 'Create Category',
    filters: ['status', 'program'],
    formFields: ['center', 'program', 'name', 'status'],
  },
  'exam-sub-category': {
    id: 'exam-sub-category',
    icon: FolderTree,
    bannerTitle: 'Exam Sub-Category',
    bannerSubtitle: 'Sub-divisions under each exam category',
    addLabel: 'Add Sub-Category',
    searchPlaceholder: 'Search Sub Category',
    primaryColumn: 'Sub-Category',
    emptyTitle: 'No Sub-Categories Found',
    emptyDescription: 'Add sub-categories under your exam categories.',
    emptyCta: 'Create Sub-Category',
    filters: ['status'],
    formFields: ['center', 'program', 'examCategory', 'name', 'status'],
  },
  courses: {
    id: 'courses',
    icon: BookOpen,
    bannerTitle: 'Courses',
    bannerSubtitle: 'Manage courses linked to programs and exam hierarchy',
    addLabel: 'Add Course',
    searchPlaceholder: 'Search courses...',
    primaryColumn: 'Course Name',
    emptyTitle: 'No Courses Found',
    emptyDescription: 'Create your first course and link it to a program and exam hierarchy.',
    emptyCta: 'Add Course',
    filters: ['status', 'centre', 'program'],
  },
  subject: {
    id: 'subject',
    icon: GraduationCap,
    bannerTitle: 'Subjects',
    bannerSubtitle: 'Subjects under courses',
    addLabel: 'Add Subject',
    searchPlaceholder: 'Search Subject',
    primaryColumn: 'Subject',
    emptyTitle: 'No Subjects Found',
    emptyDescription: 'Add subjects for your academic programs.',
    emptyCta: 'Create Subject',
    filters: ['status'],
    formFields: ['name', 'description', 'status'],
  },
  topic: {
    id: 'topic',
    icon: Layers,
    bannerTitle: 'Topics',
    bannerSubtitle: 'Topics organized under subjects',
    addLabel: 'Add Topic',
    searchPlaceholder: 'Search Topic',
    primaryColumn: 'Topic',
    emptyTitle: 'No Topics Found',
    emptyDescription: 'Organize topics under each subject.',
    emptyCta: 'Create Topic',
    filters: ['subject', 'status'],
    formFields: ['subject', 'name', 'description', 'status'],
  },
  teachers: {
    id: 'teachers',
    icon: Users,
    bannerTitle: 'Teachers',
    bannerSubtitle: 'Faculty assigned to topics',
    addLabel: 'Add Teacher',
    searchPlaceholder: 'Search teachers...',
    primaryColumn: 'Name',
    emptyTitle: 'No Teachers Found',
    emptyDescription: 'Add faculty linked to subjects.',
    emptyCta: 'Create Teacher',
    filters: ['subject', 'centre', 'status'],
    formFields: ['center', 'subject', 'name', 'description', 'status'],
    dateColumns: { created: 'Added On', modified: 'Modified On' },
  },
  city: {
    id: 'city',
    icon: MapPin,
    bannerTitle: 'City',
    bannerSubtitle: 'Manage cities and learning centers',
    addLabel: 'Add City',
    searchPlaceholder: 'Search city...',
    primaryColumn: 'Place Name',
    emptyTitle: 'No Cities Found',
    emptyDescription: 'Add cities and places linked to your centres.',
    emptyCta: 'Add City',
    filters: ['status', 'centre'],
  },
  'class-rooms': {
    id: 'class-rooms',
    icon: DoorOpen,
    bannerTitle: 'Class Rooms',
    bannerSubtitle: 'Physical rooms for live class scheduling',
    addLabel: 'Add Classroom',
    searchPlaceholder: 'Search classrooms...',
    primaryColumn: 'Classroom Name',
    emptyTitle: 'No Classrooms Found',
    emptyDescription: 'Add classrooms to assign to live sessions.',
    emptyCta: 'Add Classroom',
    filters: ['status', 'centre'],
  },
}
