/** Copy and defaults for Schedule Class / Recorded / Live Sessions list modules (not Calendar). */
export const LIVE_CLASS_MODULES = {
  schedule: {
    defaultLessonType: null,
    lockLessonType: false,
    addButtonLabel: 'Add class',
    tableItemLabel: 'lessons',
    modalTitle: 'Schedule class',
    createHeader: 'Schedule class',
    editHeader: 'Edit lesson',
    createSubmitLabel: 'Schedule class',
    updateSubmitLabel: 'Save changes',
    createSuccess: 'Class scheduled',
    updateSuccess: 'Lesson updated',
  },
  recordings: {
    defaultLessonType: 'Recording',
    lockLessonType: true,
    addButtonLabel: 'Add class',
    tableItemLabel: 'recordings',
    modalTitle: 'Recorded class',
    createHeader: 'Add recorded class',
    editHeader: 'Edit recorded class',
    createSubmitLabel: 'Save recording',
    updateSubmitLabel: 'Save changes',
    createSuccess: 'Recording saved',
    updateSuccess: 'Recording updated',
  },
  liveSessions: {
    defaultLessonType: 'Live',
    lockLessonType: true,
    addButtonLabel: 'Add class',
    tableItemLabel: 'sessions',
    modalTitle: 'Live session',
    createHeader: 'Schedule session',
    editHeader: 'Edit session',
    createSubmitLabel: 'Schedule session',
    updateSubmitLabel: 'Save changes',
    createSuccess: 'Session scheduled',
    updateSuccess: 'Session updated',
  },
}
