import { BULK_UPLOAD_ACCEPT, MAX_BULK_FILE_BYTES } from '../utils/batchTestSeriesForm'

/** Central upload profiles — formats, limits, and recommended dimensions */
export const UPLOAD_PROFILES = {
  IMAGE_STANDARD: {
    id: 'IMAGE_STANDARD',
    labelFormats: ['JPG', 'PNG', 'WEBP'],
    extensions: ['jpg', 'jpeg', 'png', 'webp'],
    mimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    accept: 'image/jpeg,image/png,image/webp,image/*',
    maxBytes: 5 * 1024 * 1024,
    recommendedDimensions: { width: 1200, height: 800 },
    minDimensions: { width: 400, height: 300 },
  },
  IMAGE_BANNER: {
    id: 'IMAGE_BANNER',
    labelFormats: ['JPG', 'PNG', 'WEBP'],
    extensions: ['jpg', 'jpeg', 'png', 'webp'],
    mimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    accept: 'image/jpeg,image/png,image/webp',
    maxBytes: 5 * 1024 * 1024,
    recommendedDimensions: { width: 1920, height: 600 },
    minDimensions: { width: 800, height: 200 },
  },
  IMAGE_THUMBNAIL: {
    id: 'IMAGE_THUMBNAIL',
    labelFormats: ['JPG', 'PNG', 'WEBP'],
    extensions: ['jpg', 'jpeg', 'png', 'webp'],
    mimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    accept: 'image/*',
    maxBytes: 2 * 1024 * 1024,
    recommendedDimensions: { width: 400, height: 400 },
  },
  IMAGE_PROFILE: {
    id: 'IMAGE_PROFILE',
    labelFormats: ['JPG', 'PNG', 'WEBP'],
    extensions: ['jpg', 'jpeg', 'png', 'webp'],
    mimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    accept: 'image/jpeg,image/png,image/webp,image/*',
    maxBytes: 2 * 1024 * 1024,
    recommendedDimensions: { width: 400, height: 400 },
    limitations: 'Square aspect ratio recommended',
  },
  IMAGE_ICON: {
    id: 'IMAGE_ICON',
    labelFormats: ['JPG', 'PNG', 'WEBP', 'SVG'],
    extensions: ['jpg', 'jpeg', 'png', 'webp', 'svg'],
    mimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml'],
    accept: 'image/jpeg,image/png,image/webp,image/svg+xml',
    maxBytes: 1 * 1024 * 1024,
    recommendedDimensions: { width: 128, height: 128 },
  },
  PDF_STANDARD: {
    id: 'PDF_STANDARD',
    labelFormats: ['PDF'],
    extensions: ['pdf'],
    mimeTypes: ['application/pdf'],
    accept: '.pdf,application/pdf',
    maxBytes: 10 * 1024 * 1024,
  },
  DOCUMENT_BOOK: {
    id: 'DOCUMENT_BOOK',
    labelFormats: ['PDF', 'EPUB', 'DOC', 'DOCX'],
    extensions: ['pdf', 'epub', 'doc', 'docx'],
    mimeTypes: [
      'application/pdf',
      'application/epub+zip',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    ],
    accept: '.pdf,.epub,.doc,.docx,application/pdf',
    maxBytes: 25 * 1024 * 1024,
  },
  EXCEL_BULK: {
    id: 'EXCEL_BULK',
    labelFormats: ['XLSX', 'CSV'],
    extensions: ['xlsx', 'csv'],
    mimeTypes: [
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'text/csv',
    ],
    accept:
      '.xlsx,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv',
    maxBytes: 15 * 1024 * 1024,
  },
  CSV_METADATA: {
    id: 'CSV_METADATA',
    labelFormats: ['CSV'],
    extensions: ['csv'],
    mimeTypes: ['text/csv', 'application/csv', 'text/plain'],
    accept: '.csv,text/csv',
    maxBytes: 5 * 1024 * 1024,
  },
  VIDEO_STANDARD: {
    id: 'VIDEO_STANDARD',
    labelFormats: ['MP4', 'MOV', 'MKV', 'AVI'],
    extensions: ['mp4', 'mov', 'mkv', 'avi'],
    mimeTypes: ['video/mp4', 'video/quicktime', 'video/x-matroska', 'video/x-msvideo'],
    accept: '.mp4,.mov,.mkv,.avi,video/mp4,video/quicktime',
    maxBytes: 100 * 1024 * 1024,
  },
  VIDEO_RECORDING: {
    id: 'VIDEO_RECORDING',
    labelFormats: ['MP4', 'MOV', 'MKV', 'AVI'],
    extensions: ['mp4', 'mov', 'mkv', 'avi'],
    mimeTypes: ['video/mp4', 'video/quicktime', 'video/x-matroska', 'video/x-msvideo'],
    accept: 'video/mp4,video/quicktime,video/x-matroska,video/avi,.mp4,.mov,.mkv,.avi',
    maxBytes: 100 * 1024 * 1024,
  },
  AUDIO_STANDARD: {
    id: 'AUDIO_STANDARD',
    labelFormats: ['MP3', 'WAV', 'M4A'],
    extensions: ['mp3', 'wav', 'm4a'],
    mimeTypes: ['audio/mpeg', 'audio/wav', 'audio/mp4', 'audio/x-m4a'],
    accept: '.mp3,.wav,.m4a,audio/mpeg,audio/wav,audio/mp4',
    maxBytes: 20 * 1024 * 1024,
  },
  CONTENT_LIBRARY_FILES: {
    id: 'CONTENT_LIBRARY_FILES',
    labelFormats: ['PDF', 'Video', 'DOC', 'PPT', 'XLS', 'ZIP', 'Images'],
    extensions: [
      'pdf',
      'mp4',
      'webm',
      'mov',
      'doc',
      'docx',
      'ppt',
      'pptx',
      'xls',
      'xlsx',
      'zip',
      'png',
      'jpg',
      'jpeg',
      'gif',
      'webp',
    ],
    mimeTypes: [],
    accept: '',
    maxBytes: 500 * 1024 * 1024,
    limitations: 'Multiple files allowed',
  },
  EXAM_BULK_DOCUMENTS: {
    id: 'EXAM_BULK_DOCUMENTS',
    labelFormats: ['PDF', 'Word', 'Excel', 'PowerPoint', 'CSV', 'TXT'],
    extensions: ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'ppt', 'pptx', 'txt', 'tsv'],
    mimeTypes: [],
    accept: BULK_UPLOAD_ACCEPT,
    maxBytes: MAX_BULK_FILE_BYTES,
    limitations: `Up to 20 files · max ${MAX_BULK_FILE_BYTES / (1024 * 1024)} MB each`,
  },
  IMAGE_MULTI: {
    id: 'IMAGE_MULTI',
    labelFormats: ['JPG', 'PNG', 'WEBP'],
    extensions: ['jpg', 'jpeg', 'png', 'webp'],
    mimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    accept: 'image/jpeg,image/png,image/webp',
    maxBytes: 5 * 1024 * 1024,
    recommendedDimensions: { width: 800, height: 1000 },
    limitations: 'Multiple images allowed',
  },
}

export const UPLOAD_PROFILE_KEYS = Object.keys(UPLOAD_PROFILES)
