import { formatINR } from '../../../utils/financeFilters'
import { formatCategoryDateTime } from '../../../utils/formatDateTime'
import FinanceStatusBadge from '../FinanceStatusBadge'
import { cn } from '../../../utils/cn'

const GST_RATE = 0.18

export default function CompletionReceiptDocument({ row, className, compact = false }) {
  if (!row) return null

  const totalFees = row.totalFees ?? row.amountPaid ?? 0
  const base = Math.round(totalFees / (1 + GST_RATE))
  const gst = totalFees - base
  const isEmi = row.receiptStatus === 'EMI Completed'

  return (
    <div
      className={cn(
        'mx-auto w-full rounded-lg border border-slate-200 bg-white shadow-inner',
        compact ? 'p-4 text-xs' : 'p-6 sm:p-8 text-sm',
        className,
      )}
      style={{ fontFamily: 'Poppins, system-ui, sans-serif' }}
    >
      <div className="flex items-start justify-between gap-3 border-b-2 border-[#1a3a5c] pb-3">
        <div className="flex items-start gap-3">
          <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg bg-gradient-to-br from-[#246392] to-[#1a4d73] text-lg font-bold text-white">
            SI
          </div>
          <div>
            <h2 className={cn('font-bold text-[#1a3a5c]', compact ? 'text-base' : 'text-xl')}>
              Sriram IAS
            </h2>
            <p className="text-[#686868]">Official Fee Receipt</p>
          </div>
        </div>
        <div className="text-right">
          <p className="font-bold text-[#246392]">{row.receiptNumber}</p>
          <p className="text-[#686868]">{formatCategoryDateTime(row.paymentDate)}</p>
          <FinanceStatusBadge status={row.receiptStatus} className="mt-1" />
        </div>
      </div>

      <div className="mt-4 grid gap-3 sm:grid-cols-2">
        <div>
          <p className="text-[10px] font-bold uppercase tracking-wide text-[#55ace7]">Student</p>
          <p className="font-bold text-[#222]">{row.studentName}</p>
          <p className="text-[#686868]">ID: {row.studentId}</p>
          <p className="text-[#686868]">{row.mobile}</p>
          <p className="text-[#686868]">{row.email}</p>
        </div>
        <div className="sm:text-right">
          <p className="text-[10px] font-bold uppercase tracking-wide text-[#55ace7]">Course</p>
          <p className="font-bold text-[#222]">{row.courseName}</p>
          <p className="text-[#686868]">
            {row.paymentTypeLabel} · {row.paymentMode}
          </p>
          <p className="text-[#686868]">{row.centerName || row.branch}</p>
        </div>
      </div>

      {isEmi && (
        <div className="mt-3 rounded-lg border border-[#246392]/20 bg-[#eef6fc] px-3 py-2 text-xs text-[#246392]">
          <strong>EMI completion:</strong>{' '}
          {row.emiCompletionNote || 'All EMI installments have been successfully completed.'}
        </div>
      )}

      <table className="mt-4 w-full border-collapse">
        <thead>
          <tr className="bg-gradient-to-r from-[#55ace7] to-[#246392] text-left text-white">
            <th className="px-2 py-1.5 font-semibold">Description</th>
            <th className="px-2 py-1.5 font-semibold">Mode</th>
            <th className="px-2 py-1.5 text-right font-semibold">Amount</th>
          </tr>
        </thead>
        <tbody>
          <tr className="border-b border-slate-100">
            <td className="px-2 py-2">{row.courseName}</td>
            <td className="px-2 py-2">{row.paymentMode}</td>
            <td className="px-2 py-2 text-right font-semibold">{formatINR(row.amountPaid)}</td>
          </tr>
        </tbody>
      </table>

      <div className="mt-4 ml-auto max-w-[200px] space-y-1 text-xs">
        <div className="flex justify-between">
          <span className="text-[#686868]">Taxable</span>
          <span>{formatINR(base)}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-[#686868]">GST 18%</span>
          <span>{formatINR(gst)}</span>
        </div>
        <div className="flex justify-between border-t border-[#1a3a5c] pt-1 text-sm font-bold text-[#1a3a5c]">
          <span>Total paid</span>
          <span>{formatINR(row.amountPaid)}</span>
        </div>
      </div>

      <p className="mt-6 text-center text-[10px] text-[#9ca0a8]">
        Generated by {row.receiptAudit?.generatedBy || 'Finance'} · GSTIN: 29ABCDESRI0001Z5
      </p>
      <div className="mt-4 flex justify-between text-[10px] text-[#555]">
        <span className="w-[40%] border-t border-slate-300 pt-2">Student signature</span>
        <span className="w-[40%] border-t border-slate-300 pt-2 text-right">Finance signature</span>
      </div>
    </div>
  )
}
